# Generated by Django 3.2.3 on 2021-05-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaiKhoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usr', models.CharField(max_length=80)),
                ('pwd', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Tuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NgayBD', models.DateField()),
                ('NgayKT', models.DateField()),
                ('sd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Thu7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
        migrations.CreateModel(
            name='Thu6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
        migrations.CreateModel(
            name='Thu5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
        migrations.CreateModel(
            name='Thu4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
        migrations.CreateModel(
            name='Thu3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
        migrations.CreateModel(
            name='Thu2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
        migrations.CreateModel(
            name='ChuNhat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThoiGianBD', models.TimeField()),
                ('ThoiGianKT', models.TimeField()),
                ('TieuDe', models.CharField(max_length=50)),
                ('NoiDung', models.CharField(max_length=80)),
                ('MatKhau', models.CharField(max_length=20)),
                ('id_tuan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LichLamViec.tuan')),
            ],
        ),
    ]
