# Generated by Django 3.2.3 on 2021-06-01 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LichLamViec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatKhauXemLich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MatKhau', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='chunhat',
            name='MatKhau',
        ),
        migrations.RemoveField(
            model_name='thu2',
            name='MatKhau',
        ),
        migrations.RemoveField(
            model_name='thu3',
            name='MatKhau',
        ),
        migrations.RemoveField(
            model_name='thu4',
            name='MatKhau',
        ),
        migrations.RemoveField(
            model_name='thu5',
            name='MatKhau',
        ),
        migrations.RemoveField(
            model_name='thu6',
            name='MatKhau',
        ),
        migrations.RemoveField(
            model_name='thu7',
            name='MatKhau',
        ),
        migrations.AddField(
            model_name='taikhoan',
            name='mail',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
    ]
