# Generated by Django 3.2.3 on 2021-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LichLamViec', '0002_auto_20210601_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='matkhauxemlich',
            name='sd',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
